existingObjstoreSecret: thanos-config

storegateway:
  enabled: true
  serviceAccount:
    existingServiceAccount: thanos

query:
  enabled: true
  logLevel: debug
  replicaLabel: [prometheus_replica]
  dnsDiscovery:
    sidecarsService: prometheus-kube-prometheus-prometheus-thanos
  stores:
    - dnssrv+_grpc._tcp.192.168.255.144:10901
