{{ if .Values.installation.enabled }}
apiVersion: operator.tigera.io/v1
kind: Installation
metadata:
  name: default
spec:
  kubernetesProvider: {{ .Values.installation.kubernetesProvider }}
  cni:
    type: Calico
  calicoNetwork:
    bgp: {{ .Values.installation.calicoNetwork.bgp }}
    ipPools:
{{ toYaml  .Values.installation.calicoNetwork.ipPools | indent 4 }}

{{ end }}

{{ if .Values.apiServer.enabled }}
---
apiVersion: operator.tigera.io/v1
kind: APIServer
metadata:
  name: default
spec: {}

{{ end }}
