apiVersion: v1
kind: Secret
metadata:
  name: thanos-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-1"
stringData:
  objstore.yml: |
    type: S3
    config:
      bucket: prometheus-cloudops-1634
      endpoint: s3.eu-west-1.amazonaws.com
      trace:
        enable: true
      aws_sdk_auth: true
